# Generated by Django 4.1.8 on 2023-04-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_medorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedOrder',
            new_name='MedOrder_interm',
        ),
    ]
