# Generated by Django 4.1.8 on 2023-04-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_medorder_interm_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medorder_interm',
            old_name='user',
            new_name='user_id',
        ),
    ]
