# Generated by Django 4.1.8 on 2023-04-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_rename_user_id_medorder_interm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorder_interm',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
