# Generated by Django 4.1.8 on 2023-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_user_medorder_interm_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medorder_interm',
            old_name='user_id',
            new_name='user',
        ),
    ]
