# Generated by Django 4.1.8 on 2023-04-19 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_rename_user_id_medorder_interm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorder_interm',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
