# Generated by Django 4.1.8 on 2023-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_medorder_interm_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorder_interm',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medorder_interm',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
