# Generated by Django 4.1.8 on 2023-04-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_medorder_interm_update_alter_medorder_interm_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medorder_interm',
            old_name='p_id',
            new_name='p',
        ),
    ]
