# Generated by Django 4.1.8 on 2023-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_rename_p_id_medorder_interm_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='medorder_interm',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
