# Generated by Django 4.1.8 on 2023-04-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_completeorder_medorder_interm_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteOrder',
        ),
    ]
