# Generated by Django 4.1.8 on 2023-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_delete_completeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorder_interm',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
